name: 'task_monitoring'
version: '1.0.0'
config-version: 2

profile: 'task_monitoring'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  task_monitoring:
    materialized: table
    exports:
      +materialized: table
      schema: exports
