services:
  clickhouse:
    build:
      context: ./clickhouse
    image: champion_robin/clickhouse
    container_name: clickhouse
    env_file:
      - ./.env
      - ./clickhouse/.env
    ports:
      - "8123:8123"  # HTTP interface
      - "9000:9000"  # Native interface
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - analytics-network

  oracle-sync:
    build: ./oracle-sync
    container_name: oracle-sync
    depends_on:
      - clickhouse
    environment:
      - ORACLE_USER=${ORACLE_USER}
      - ORACLE_SYNC_PASSWORD=${ORACLE_SYNC_PASSWORD}
      - ORACLE_DSN=${ORACLE_DSN}
      - ORACLE_HOST=${ORACLE_HOST}
      - ORACLE_PORT=${ORACLE_PORT}
      - ORACLE_SERVICE=${ORACLE_SERVICE}
      - CLICKHOUSE_HOST=clickhouse
      - CLICKHOUSE_USER=${CLICKHOUSE_USER}
      - CLICKHOUSE_PASSWORD=default
      - CLICKHOUSE_PORT=9000
      - CLICKHOUSE_HTTP_PORT=8123
      - CLICKHOUSE_DB=${CLICKHOUSE_DB}
    volumes:
      - ./oracle-sync:/app
    command: ["./wait-for-it.sh", "clickhouse:9000", "--", "python", "sync.py"]
    networks:
      - analytics-network
      - external-network  # For reaching Oracle server

  cubejs:
    image: cubejs/cube:latest
    build:
      context: ./cubejs
    container_name: cubejs
    depends_on:
      - clickhouse
    ports:
      - 4000:4000
      - 15432:15432  # SQL API port
    environment:
          # Default/primary database
      - CUBEJS_DB_TYPE=clickhouse
      - CUBEJS_DB_NAME=support_analytics
      - CUBEJS_DB_HOST=clickhouse
      - CUBEJS_DB_USER=default
      - CUBEJS_DB_PASS=default
      - CUBEJS_DB_PORT=8123
      - CUBEJS_PG_SQL_PORT=15432      # SQL API credential
      - CUBEJS_SQL_USER=cube          # SQL API credential
      - CUBEJS_SQL_PASSWORD=cube

      - CUBEJS_API_SECRET=${CUBEJS_API_SECRET}
      - CUBEJS_DEV_MODE=${CUBEJS_DEV_MODE}
    volumes:
      - ./cubejs/schema:/cube/schema
      - ./cubejs/cube.js:/cube/cube.js
    networks:
      - analytics-network

  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    ports:
      - "3000:3000"
    environment:
      - MB_DB_TYPE=h2
      - MB_DB_FILE=/metabase-data/metabase.db
    volumes:
      - ./metabase/metabase-data:/metabase-data
    networks:
      - analytics-network

networks:
  analytics-network:
    driver: bridge
  external-network:
    driver: bridge
    ipam:
      config:
        - subnet: ${EXTERNAL_NETWORK_SUBNET}

volumes:
  clickhouse_data:
